name: Docker Release

on:
  push:
    tags:
      - "*"

env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push_base:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    name: Tag Release (Base FPM, ${{ matrix.base-tag }})

    strategy:
      fail-fast: false
      matrix:
        base-tag:
          - 7.4-fpm-alpine
          - 8.0-fpm-alpine
          - 8.1-fpm-alpine

    steps:
      - uses: actions/checkout@v3

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: colite-commerce/docker-base
          tags: |
            type=semver,pattern={{version}}-${{ matrix.base-tag }}
            type=semver,pattern={{major}}.{{minor}}-${{ matrix.base-tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        id: docker
        uses: docker/build-push-action@v3
        with:
          load: true
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          file: Dockerfile.base
          build-args: |
            BASE_TAG=${{ matrix.base-tag }}

  push_api:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    name: Tag Release (API, ${{ matrix.base-tag }})

    strategy:
      matrix:
        base-tag:
          - 4.8-php8.0-alpine
          - 4.7-php8.0-alpine
          - 4.6-php8.0-alpine
          - 4.8-php8.1-alpine
          # - 4.7-php8.1-alpine
          # - 4.6-php8.1-alpine

    steps:
      - uses: actions/checkout@v3

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: colite-commerce/docker-base
          tags: |
            type=semver,pattern=api-{{version}}-${{ matrix.base-tag }}
            type=semver,pattern=api-{{major}}.{{minor}}-${{ matrix.base-tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        id: docker
        uses: docker/build-push-action@v3
        with:
          load: true
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          file: Dockerfile.api
          build-args: |
            BASE_TAG=${{ matrix.base-tag }}

  push_worker:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    name: Tag Release (Worker, ${{ matrix.base-tag }})

    strategy:
      matrix:
        base-tag:
          - 8.1-cli-alpine
          - 8.0-cli-alpine
          - 7.4-cli-alpine

    steps:
      - uses: actions/checkout@v3

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: colite-commerce/docker-base
          tags: |
            type=semver,pattern=worker-{{version}}-${{ matrix.base-tag }}
            type=semver,pattern=worker-{{major}}.{{minor}}-${{ matrix.base-tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        id: docker
        uses: docker/build-push-action@v3
        with:
          load: true
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          file: Dockerfile.worker
          build-args: |
            BASE_TAG=${{ matrix.base-tag }}
